import { Button } from "@/components/ui/button"
import { cn } from "@/lib/utils"
import { TimeEntryType } from "@/types/time-entry"

interface TimeEntryButtonProps {
  type: TimeEntryType
  onClick: () => void
  disabled?: boolean
  className?: string
}

export function TimeEntryButton({
  type,
  onClick,
  disabled = false,
  className,
}: TimeEntryButtonProps) {
  const variants: Record<TimeEntryType, { label: string, variant: "default" | "secondary" | "outline" | "destructive" }> = {
    "entrada": { label: "Registrar Entrada", variant: "default" },
    "pausaCafe": { label: "Registrar Pausa Café", variant: "secondary" },
    "pausaComida": { label: "Registrar Pausa Comida", variant: "secondary" },
    "otros": { label: "Registrar Otros", variant: "outline" },
    "salida": { label: "Registrar Salida", variant: "destructive" },
  }

  const { label, variant } = variants[type]

  return (
    <Button
      variant={variant}
      onClick={onClick}
      disabled={disabled}
      className={cn("w-full", className)}
    >
      {label}
    </Button>
  )
}

// Generated by Copilot
