import { useState, useEffect } from "react"
import { formatElapsedTime } from "@/lib/date-utils"

interface TimeDisplayProps {
  startTime: Date
  label: string
  className?: string
}

export function TimeDisplay({ startTime, label, className }: TimeDisplayProps) {
  const [elapsedTime, setElapsedTime] = useState("00:00:00")
  
  useEffect(() => {
    // Actualizar tiempo transcurrido inmediatamente
    setElapsedTime(formatElapsedTime(startTime, new Date()))
    
    // Actualizar cada segundo
    const interval = setInterval(() => {
      setElapsedTime(formatElapsedTime(startTime, new Date()))
    }, 1000)
    
    return () => clearInterval(interval)
  }, [startTime])
  
  return (
    <div className={className}>
      <div className="text-sm text-muted-foreground mb-1">
        {label}
      </div>
      <div className="font-mono text-2xl font-semibold">
        {elapsedTime}
      </div>
    </div>
  )
}

// Generated by Copilot
