import { redirect } from 'next/navigation'

export default function Home() {
  // Redirect to dashboard if logged in, otherwise to login
  // This would normally check for authentication
  return redirect('/dashboard')
  
  // Generated by Copilot
}
