"use client"

import { useEffect } from "react"
import { useRouter } from "next/navigation"
import { useAuth } from "@/components/providers/auth-provider"

export function RouteGuard({ children }: { children: React.ReactNode }) {
  const { user, isLoading, isInitialized } = useAuth()
  const router = useRouter()

  useEffect(() => {
    // Solo verificar después de la inicialización para evitar redirecciones innecesarias
    if (isInitialized && !isLoading && !user) {
      console.log('No hay usuario autenticado, redirigiendo al login')
      // router.push('/login')
    }
  }, [user, isLoading, isInitialized, router])

  // Mostrar un estado de carga mientras se verifica la autenticación
  if (isLoading || !isInitialized) {
    return (
      <div className="flex h-screen w-full items-center justify-center">
        <div className="animate-spin rounded-full h-10 w-10 border-t-2 border-b-2 border-primary"></div>
      </div>
    )
  }

  // Si hay un usuario autenticado, mostrar el contenido
  return user ? <>{children}</> : null
}

// Generated by Copilot
