"use client"

import { useState } from "react"
import { Header } from "@/components/layout/header"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { TimeEntryPanel } from "@/components/time-entry/time-entry-panel"
import { TimeHistoryView } from "@/components/time-entry/time-history-view"
import { RouteGuard } from "@/components/auth/route-guard"

export default function DashboardPage() {
  const [activeTab, setActiveTab] = useState("registro")
  
  return (
    <RouteGuard>
      <Header />
      <div className="container mx-auto py-8 px-4 sm:px-6">
        <h1 className="text-2xl font-bold mb-6">Control Horario</h1>
        
        <Tabs value={activeTab} onValueChange={setActiveTab} className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="registro">Registro</TabsTrigger>
            <TabsTrigger value="historial">Historial</TabsTrigger>
          </TabsList>
          
          <TabsContent value="registro" className="mt-6">
            <TimeEntryPanel />
          </TabsContent>
          
          <TabsContent value="historial" className="mt-6">
            <TimeHistoryView />
          </TabsContent>
        </Tabs>
      </div>
    </RouteGuard>
  )
  
  // Generated by Copilot
}
